micronaut:
  server:
    port: 8080
  application:
    name: falsehonesty-backend
lights:
  apikey: none
  impl: lifx # Can be lifx, noop, ...
notifications:
  user: none
  token: none
  impl: pushover # can be pushover, noop, ...
